n_debug_test = 45
n_debug_code = 45
 
#List for Debug data
# file = [date, debug_total, debug_max, debug_max_name, debug_min, debug_min_name]
# file = [  0 ,      1     ,     2    ,       3       ,    4     ,       5       ]
debug_code = [['2017_08_23', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '38'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_08_24', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '38'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_08_25', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '38'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_08_26', ['cytron_g15_servo.h', '0'], ['cytron_g15_servo.cpp', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '39'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_08_27', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '40'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_08_28', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.h', '0'], ['joint_handler.cpp', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '28'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_08_29', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h.gch', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.cpp', '0'], ['joint_handler.h', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '28'], ['main.cpp', '0']] ,\
['2017_08_30', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['cytron_g15_servo.h.gch', '0'], ['joint_handler.h', '0'], ['joint_handler.cpp', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '28'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_08_31', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['cytron_g15_servo.h.gch', '0'], ['joint_handler.h', '0'], ['joint_handler.cpp', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '28'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['main.cpp', '0']] ,\
['2017_09_07', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h.gch', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.cpp', '0'], ['joint_handler.h', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '28'], ['main.cpp', '0']] ,\
['2017_09_08', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.cpp', '0'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '28'], ['main.cpp', '0'], ['utilities.h', '30']] ,\
['2017_09_09', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.cpp', '0'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '28'], ['main.cpp', '2'], ['utilities.h', '59']] ,\
['2017_09_11', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.h', '0'], ['joint_handler.cpp', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.cpp', '28'], ['servo_rha.h', '0'], ['main.cpp', '2'], ['utilities.h', '59']] ,\
['2017_09_12', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.cpp', '0'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '28'], ['main.cpp', '2'], ['utilities.h', '63'], ['utilities.h.gch', '0']] ,\
['2017_09_13', ['cytron_g15_servo.cpp', '0'], ['cytron_g15_servo.h', '0'], ['joint_handler.cpp', '0'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '30'], ['main.cpp', '2'], ['utilities.cpp', '71'], ['utilities.h', '10'], ['utilities.h.gch', '0']] ,\
['2017_09_14', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['joint_handler.cpp', '0'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '30'], ['main.cpp', '2'], ['utilities.cpp', '71'], ['utilities.h', '10'], ['utilities.h.gch', '0']] ,\
['2017_09_15', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['joint_handler.cpp', '4'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '28'], ['main.cpp', '2'], ['utilities.cpp', '71'], ['utilities.h', '10'], ['utilities.h.gch', '0']] ,\
['2017_09_16', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['joint_handler.cpp', '7'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['rha_types.h', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '22'], ['main.cpp', '2'], ['utilities.cpp', '71'], ['utilities.h', '10'], ['utilities.h.gch', '0']] ,\
['2017_09_17', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['joint_handler.cpp', '7'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['rha_types.h', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '22'], ['main.cpp', '2'], ['utilities.cpp', '71'], ['utilities.h', '10'], ['utilities.h.gch', '0']] ,\
['2017_09_19', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['joint_handler.cpp', '18'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '0'], ['readme.txt', '0'], ['rha_types.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '10'], ['utilities.cpp', '71'], ['utilities.h', '16'], ['main.cpp', '0']] ,\
['2017_09_20', ['cytron_g15_servo.h.txt', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['joint_handler.h.gch', '0'], ['joint_handler.h', '0'], ['joint_handler.cpp', '18'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h', '0'], ['servo_rha.cpp', '14'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['utilities.h', '16'], ['utilities.cpp', '71'], ['main.cpp', '0']] ,\
['2017_09_21', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '27'], ['joint_handler.h', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h', '6'], ['servo_rha.h', '0'], ['servo_rha.cpp', '14'], ['utilities.cpp', '10'], ['utilities.h', '30'], ['main.cpp', '0']] ,\
['2017_09_22', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '28'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '14'], ['utilities.cpp', '10'], ['utilities.h', '30'], ['main.cpp', '0']] ,\
['2017_09_23', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '29'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '14'], ['utilities.cpp.old', '10'], ['utilities.cpp', '38'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_09_24', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '30'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '14'], ['utilities.cpp.old', '10'], ['utilities.cpp', '38'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_09_25', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '30'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '14'], ['utilities.cpp.old', '10'], ['utilities.cpp', '38'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_09_26', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '30'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '14'], ['utilities.cpp.old', '10'], ['utilities.cpp', '38'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_09_28', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '30'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '7'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '14'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_09_29', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '30'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_09_30', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '30'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_10_31', ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '30'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '0'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_11_01', ['WiiChuck.h', '0'], ['chickconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '0'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_11_02', ['WiiChuck.h', '0'], ['chickconnection.jpg', '0'], ['chuck_handler.h', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '0'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_11_03', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '0'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_11_07', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '9'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_11_21', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '9'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_12_21', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '9'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_12_22', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['FuzzyRegulator.h', '0'], ['rha_types.h.gch', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '9'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '19'], ['utilities.cpp.old', '10'], ['utilities.cpp', '40'], ['utilities.h', '0'], ['main.cpp', '0']] ,\
['2017_12_23', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['rha_types.h.gch', '0'], ['fuzzy_regulator.h', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '10'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '26'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp', '0'], ['main_utilities.cpp_', '0']] ,\
['2017_12_25', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '34'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['rha_types.h.gch', '0'], ['fuzzy_regulator.h', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '10'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '26'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp', '0'], ['main_utilities.cpp_', '0']] ,\
['2017_12_26', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '36'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['rha_types.h.gch', '0'], ['fuzzy_regulator.h', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '10'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '30'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp_', '0'], ['main_utilities.cpp', '0']] ,\
['2017_12_27', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '36'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['rha_types.h.gch', '0'], ['fuzzy_regulator.h', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '10'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '30'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp_', '0'], ['main_utilities.cpp', '0']] ,\
['2018_01_01', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '36'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['rha_types.h.gch', '0'], ['fuzzy_regulator.h', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '10'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '30'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp_', '0'], ['main_utilities.cpp', '0']] ,\
['2018_01_07', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '36'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['rha_types.h.gch', '0'], ['fuzzy_regulator.h', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '10'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '30'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp_', '0'], ['main_utilities.cpp', '0']] ,\
['2018_01_18', ['WiiChuck.h', '0'], ['chuck_handler.h', '0'], ['chuckconnection.jpg', '0'], ['cytron_g15_servo.cpp.txt', '0'], ['cytron_g15_servo.h.txt', '0'], ['debug.cpp', '0'], ['joint_handler.cpp', '36'], ['joint_handler.h', '0'], ['joint_handler.h.gch', '0'], ['joint_rha.h.gch', '0'], ['joint_rha.h', '0'], ['joint_rha.cpp', '2'], ['readme.txt', '0'], ['pid_regulator.h', '0'], ['rha_types.h.gch', '0'], ['fuzzy_regulator.h', '0'], ['rha_types.h', '6'], ['robot_rha.cpp', '10'], ['robot_rha.h.gch', '0'], ['robot_rha.h~', '0'], ['robot_rha.h', '0'], ['servo_rha.h.gch', '0'], ['servo_rha.h', '0'], ['servo_rha.cpp', '30'], ['utilities.cpp.old', '10'], ['utilities.cpp', '39'], ['utilities.h', '0'], ['main.cpp', '0'], ['main_utilities.cpp_', '0']] ,\
[0]]

debug_test = [['2017_08_23', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '8']] ,\
['2017_08_24', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '8']] ,\
['2017_08_25', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '8']] ,\
['2017_08_26', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '29']] ,\
['2017_08_27', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '29']] ,\
['2017_08_28', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_08_29', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_08_30', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_08_31', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_07', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_08', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_09', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_11', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_12', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_13', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_14', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_15', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_16', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_17', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_19', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_20', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_21', ['test_cytron_g15_servo.cpp', '6'], ['test_servo_mock.cpp', '3'], ['test_servo_real.cpp', '11']] ,\
['2017_09_22', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '2']] ,\
['2017_09_23', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_09_24', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_09_25', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_09_26', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_09_28', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_09_29', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_09_30', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_10_31', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_11_01', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_11_02', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_11_03', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_11_07', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_11_21', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_12_21', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_12_22', ['test_servo_rha.cpp', '0'], ['test_joint_rha.cpp', '6'], ['test_joint_handler.cpp', '4']] ,\
['2017_12_23', ['test_rha_types.cpp', '0'], ['test_pid_regulator.cpp', '0'], ['test_fuzzy_regulator.cpp', '0'], ['test_servo_rha.cpp', '6'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '4'], ['log_test_2017-12-23_19', '44.log', '0'], ['perform_test.sh', '0']] ,\
['2017_12_25', ['test_rha_types.cpp', '0'], ['test_pid_regulator.cpp', '0'], ['test_fuzzy_regulator.cpp', '0'], ['test_servo_rha.cpp', '6'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '4'], ['log_test_2017-12-23_19', '44.log', '0'], ['perform_test.sh', '0']] ,\
['2017_12_26', ['test_rha_types.cpp', '0'], ['test_pid_regulator.cpp', '0'], ['test_fuzzy_regulator.cpp', '0'], ['test_servo_rha.cpp', '6'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '4'], ['log_execution.log', '0'], ['log_test_2017-12-23_19', '44.log', '0'], ['perform_test.sh', '0']] ,\
['2017_12_27', ['test_rha_types.cpp', '0'], ['test_pid_regulator.cpp', '0'], ['test_fuzzy_regulator.cpp', '0'], ['test_servo_rha.cpp', '6'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '4'], ['log_execution.log', '0'], ['log_test_2017-12-23_19', '44.log', '0'], ['perform_test.sh', '0'], ['perform_test.sh.save', '0']] ,\
['2018_01_01', ['test_rha_types.cpp', '0'], ['test_pid_regulator.cpp', '0'], ['test_fuzzy_regulator.cpp', '0'], ['test_servo_rha.cpp', '6'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '4'], ['log_execution.log', '0'], ['log_test_2017-12-23_19', '44.log', '0'], ['perform_test.sh', '0'], ['perform_test.sh.save', '0']] ,\
['2018_01_07', ['test_rha_types.cpp', '0'], ['test_pid_regulator.cpp', '0'], ['test_fuzzy_regulator.cpp', '0'], ['test_servo_rha.cpp', '6'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '4'], ['log_execution.log', '0'], ['log_test_2017-12-23_19', '44.log', '0'], ['perform_test.sh', '0'], ['perform_test.sh.save', '0']] ,\
['2018_01_18', ['test_rha_types.cpp', '0'], ['test_pid_regulator.cpp', '0'], ['test_fuzzy_regulator.cpp', '0'], ['test_servo_rha.cpp', '6'], ['test_joint_rha.cpp', '0'], ['test_joint_handler.cpp', '4'], ['log_execution.log', '0'], ['log_test_2017-12-23_19', '44.log', '0'], ['perform_test.sh', '0'], ['perform_test.sh.save', '0']] ,\
[0]]

